name: github action practice
on: push
jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: run lint
        run: npm run lint
  test: 
    runs-on: ubuntu-latest
    steps:
      needs: lint
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: run test
        run: npm run test
  deploy: 
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: deploy
        run: echo "Deploying to production server"
          